export const SET_AUTH_STATE = 'AUTH/SET_AUTH_STATE'
export const SET_CURRENT_USER = 'AUTH/SET_CURRENT_USER'
export const SET_LOADING_STATUS = 'AUTH/SET_LOADING_STATUS'

export const SET_POSTS = 'SET_POSTS'
